spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: blogapi
    password: Blogapi.2023
    # password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

cors:
  allowedOrings: '*'
server:
  port: 7001
